### ISSUE TITLE
doc : how to build theme

### ISSUE THREAD

**Issue by SebSept** [AkazieIT/grav-theme-akazie-wood#5]
Great work, thanks for sharing.

I've made a child theme. 
Now I'd like to customize colors.
I changed in user/themes/mychildtheme/scss/design/_variables.scss
How can I rebuild the css ?

I run `npm install`, it's ok, then what ? Can you help me please ?

**Comment by Memurame** [comment]
First run ´npm install´, After that you have to run ´npm dep-update´.
Finaly you create the new builds with ´npm build´.

Does it help you?

**Comment by SebSept** [comment]
Thanks for feedback.
`npm install` is ok
(I installed gulp) then
`gulp dep-update` fails 

>  gulp dep-update
[18:09:03] Requiring external module @babel/register
/home/htdocs/public/pro/kine/user/themes/xxx/gulpfile.babel.js:1
import gulp from 'gulp';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Module._compile (/home/htdocs/public/pro/kine/user/themes/xxx/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.newLoader [as .js] (/home/htdocs/public/pro/kine/user/themes/xxx/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)

I tried to solve this, but it leads to other problems.

Maybe, it will be easy if I use the node version you used. 
Which node version did you use ?

**Comment by Memurame** [comment]
On my Windows i use npm 6.14.4 and on Mac 6.10.3.

I made adjustments in the [package.json](https://github.com/AkazieIT/grav-theme-akazie-wood/blob/master/package.json). You can download the latest version and copy it to the folder. After that you can run after npm install, npm run dep and npm run build. This worked for all of my tests that I did.

A new release will come soon.

**Comment by SebSept** [comment]
That did not succeed :/ with both node versions with and without the the new package.json

I'll give the errors later..

**Comment by SebSept** [comment]
```bash
» cd user/themes/akazie-wood
» gulp -v
CLI version: 2.2.0
Local version: 4.0.2
» rm package.json
» wget https://raw.githubusercontent.com/AkazieIT/grav-theme-akazie-wood/master/package.json --output-document=package.json
» rm -rf node_modules
» rm package-lock.json
» nvm install 6.14.4
v6.14.4 is already installed.
Now using node v6.14.4 (npm v3.10.10)
npm install
```
full output here : https://paste.ubuntu.com/p/7Qq6XcgRRY/
```bash
» npm run dep                                                                                                     seb@localhost

> akazie-wood@1.0.0 dep /home/htdocs/public/pro/kine/user/themes/akazie-wood
> gulp dep-update

[16:09:52] Requiring external module @babel/register
[16:09:54] Using gulpfile /home/htdocs/public/pro/kine/user/themes/akazie-wood/gulpfile.babel.js
[16:09:54] Starting 'dep-update'...
[16:09:54] Starting 'core-clean'...
[16:09:54] Finished 'core-clean' after 8.71 ms
[16:09:54] Starting 'dep-scss'...
[16:09:54] 'dep-scss' errored after 663 μs
[16:09:54] TypeError: Object.entries is not a function
    at /home/htdocs/public/pro/kine/user/themes/akazie-wood/gulpfile.babel.js:188:37
    at taskWrapper (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[16:09:54] 'dep-update' errored after 23 ms

npm ERR! Linux 5.5.11-200.fc31.x86_64
npm ERR! argv "/home/seb/.nvm/versions/node/v6.14.4/bin/node" "/home/seb/.nvm/versions/node/v6.14.4/bin/npm" "run" "dep"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! akazie-wood@1.0.0 dep: `gulp dep-update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akazie-wood@1.0.0 dep script 'gulp dep-update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the akazie-wood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dep-update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs akazie-wood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls akazie-wood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/htdocs/public/pro/kine/user/themes/akazie-wood/npm-debug.log
```
npm-debug.log : https://paste.ubuntu.com/p/QNh3T5F27J/

```
> npm run build
> akazie-wood@1.0.0 build /home/htdocs/public/pro/kine/user/themes/akazie-wood
> gulp build

[16:16:49] Requiring external module @babel/register
[16:16:50] Using gulpfile /home/htdocs/public/pro/kine/user/themes/akazie-wood/gulpfile.babel.js
[16:16:50] Starting 'build'...
[16:16:50] Starting 'css'...
[16:16:50] Starting 'css-scss-main'...
Error in plugin "sass"
Message:
    scss/main.scss
Error: File to import not found or unreadable: core/bootstrap/functions.
        on line 2 of scss/main.scss
>> @import "core/bootstrap/functions";

   ^

[16:16:50] Finished 'css-scss-main' after 26 ms
[16:16:50] Starting 'css-min-main'...
[16:16:50] Finished 'css-min-main' after 396 ms
[16:16:50] Finished 'css' after 424 ms
[16:16:50] Starting 'js'...
[16:16:50] Starting 'js-core'...
[16:16:50] 'js-core' errored after 3.78 ms
[16:16:50] Error: File not found with singular glob: /home/htdocs/public/pro/kine/user/themes/akazie-wood/js/core/jquery.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob-stream/readable.js:84:17)
    at Glob.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob/glob.js:197:8)
    at done (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob/glob.js:688:12)
    at /home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/glob/glob.js:764:12)
[16:16:50] 'js' errored after 5.41 ms
[16:16:50] 'build' errored after 430 ms

npm ERR! Linux 5.5.11-200.fc31.x86_64
npm ERR! argv "/home/seb/.nvm/versions/node/v6.14.4/bin/node" "/home/seb/.nvm/versions/node/v6.14.4/bin/npm" "run" "build"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! akazie-wood@1.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akazie-wood@1.0.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the akazie-wood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs akazie-wood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls akazie-wood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     
```
```
> cat /home/htdocs/public/pro/kine/user/themes/akazie-wood/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/seb/.nvm/versions/node/v6.14.4/bin/node',
1 verbose cli   '/home/seb/.nvm/versions/node/v6.14.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.14.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle akazie-wood@1.0.0~prebuild: akazie-wood@1.0.0
6 silly lifecycle akazie-wood@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle akazie-wood@1.0.0~build: akazie-wood@1.0.0
8 verbose lifecycle akazie-wood@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle akazie-wood@1.0.0~build: PATH: /home/seb/.nvm/versions/node/v6.14.4/lib/node_modules/npm/bin/node-gyp-bin:/home/htdocs/public/pro/kine/user/themes/akazie-wood/node_modules/.bin:/home/seb/.nvm/versions/node/v6.14.4/bin:/home/seb/.symfony/bin:/home/donnees/docs/dev/android/platform-tools:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/seb/.local/bin:/home/seb/bin:/home/seb/.composer/vendor/bin/
10 verbose lifecycle akazie-wood@1.0.0~build: CWD: /home/htdocs/public/pro/kine/user/themes/akazie-wood
11 silly lifecycle akazie-wood@1.0.0~build: Args: [ '-c', 'gulp build' ]
12 silly lifecycle akazie-wood@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle akazie-wood@1.0.0~build: Failed to exec build script
14 verbose stack Error: akazie-wood@1.0.0 build: `gulp build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/seb/.nvm/versions/node/v6.14.4/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/seb/.nvm/versions/node/v6.14.4/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid akazie-wood@1.0.0
16 verbose cwd /home/htdocs/public/pro/kine/user/themes/akazie-wood
17 error Linux 5.5.11-200.fc31.x86_64
18 error argv "/home/seb/.nvm/versions/node/v6.14.4/bin/node" "/home/seb/.nvm/versions/node/v6.14.4/bin/npm" "run" "build"
19 error node v6.14.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error akazie-wood@1.0.0 build: `gulp build`
22 error Exit status 1
23 error Failed at the akazie-wood@1.0.0 build script 'gulp build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the akazie-wood package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs akazie-wood
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls akazie-wood
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SebSept** [comment]
Also fails with node 6.10.3
```
> nvm install 6.10.3
v6.10.3 is already installed.
Now using node v6.10.3 (npm v3.10.10)
> npm install 
```
-> https://paste.ubuntu.com/p/5npq76tm3x/
```
» gulp dep-update    
```
-> https://paste.ubuntu.com/p/ST4sT8Ts6q/
```
gulp build
```
-> https://paste.ubuntu.com/p/VYXTBcZ24F/

**Comment by SebSept** [comment]
But for now, I just discovered that the theme can be customize using the file [akazie-wood.yaml](https://github.com/AkazieIT/grav-theme-akazie-wood/blob/master/akazie-wood.yaml).
Maybe that will do the job..

**Comment by SebSept** [comment]
And also using the user/themes/xxx/templates/partials/custom-css.html.twig
A lot can be customized.
So I have no need to recompile assets anymore.
Thanks for the support.
